export enum ActionTypes {
  INIT_POSTS = "INIT_POSTS",
  REMOVE_POSTS = "REMOVE_POSTS",
  FETCH_POSTS_FAILED = "REMOVE_POSTS",
  ADD_POST = "ADD_POST",
  UPVOTE = "UPVOTE",
  DOWNVOTE = "DOWNVOTE",
  USER_INIT = "USER_INIT",
  USER_POSTS = "USER_POSTS",
  EDIT_POST = "EDIT_POST",
  DELETE_POST = "DELETE_POST",
  REDIRECT_URL = "REDIRECT_URL",
  LOGOUT_USER = "LOGOUT_USER",
}
